projects:
  app:
    name: app
    schema: '.wundergraph/generated/wundergraph.schema.graphql'
    documents: '.wundergraph/operations/**/*.graphql'
    extensions:
      endpoint:
        introspect: false
        url: 'http://localhost:9991/graphql'
        headers:
          user-agent: 'WunderGraph Client'